revision: 1
schema-version: 5
owner-ms-alias: adegeo

config:
  DocMetadata:
    Headers:
      - ["---", "#### "]

    ParserRegex: "^\\* (.*): (.*)$"

    ContentUrlRegex:
      - "### Page URL\n\n(.*)"

issues:

  labeled:

    # Temporary label to mark issues as updated for Quest. The label is instantly removed
    - check:
        - type: query
          value: "length(Issue.Labels[?Name == ':world_map: mapQUEST']) != `0`"
      pass:
        - labels-remove: [":world_map: mapQUEST"]

projects_v2_item:

  reordered:

    - labels-add: [":world_map: mapQUEST"]

  edited:

    - check:
        - type: query
          value: "EventPayload.changes.field_value.field_name == 'Priority' || EventPayload.changes.field_value.field_name == 'Size'"
      pass:
        - labels-add: [":world_map: mapQUEST"]
