name: Clean repo
description: Automatically clean up unused files and replace links in a DocFx repo.
author: Genevieve Warren
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'sliders'
  color: 'purple'
inputs:
  function:
    description: 'The function you want to run: FindOrphanedArticles, FindOrphanedImages, FindOrphanedIncludes, FindOrphanedSnippets, CatalogImages, CatalogImagesWithText, FilterImagesForText, ReplaceRedirectTargets, ReplaceWithRelativeLinks, or RemoveRedirectHops.'
    required: true
  docfx_directory:
    description: 'The directory that contains the docfx.json file for the docset.'
    required: true
  target_directory:
    description: 'The top-level directory that you want to "clean".'
    required: true
  url_base_path:
    description: 'The URL base path for your docset, for example, /dotnet or /windows/uwp.'
    required: true
runs:
  using: docker
  image: ../cleanrepo.Dockerfile
  args:
    - '/Options:Function'
    - ${{ inputs.function }}
    - '/Options:DocFxDirectory'
    - ${{ inputs.docfx_directory }}
    - '/Options:TargetDirectory'
    - ${{ inputs.target_directory }}
    - '/Options:UrlBasePath'
    - ${{ inputs.url_base_path }}
