name: dotnet build and test

on:
  push:
    branches: [ main ]
    paths-ignore:
    - README.md
    - 'actions/status-checker/**' # Ignore the TypeScript action.
  pull_request:
    branches: [ main ]
    paths-ignore:
    - README.md
    - 'actions/status-checker/**' # Ignore the TypeScript action.
  workflow_dispatch:
    inputs:
      reason:
        description: The reason for running the workflow
        required: true
        default: Manual run

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: 'Print manual run reason'
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo 'Reason: ${{ github.event.inputs.reason }}'
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies for .NET docs tools
      run: |
        dotnet restore docs-tools.sln
      
    - name: Build .NET docs tools
      run: |
        dotnet build docs-tools.sln --configuration Release --no-restore

  test:
    name: test
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@main
    
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 9.0.x

    - name: Run tests
      run: |
        dotnet test docs-tools.sln --verbosity normal
